### PR TITLE
Update socket rocket to 0.4

### PR DESCRIPTION
**Pull request by hamchapman**
All the tests still pass and I tried it out in the sample app and everything looked to be working as expected.

Also fixed a few other things as I came to them, as noted in the commit messages.

### CODE REVIEW

**Comment by brandons** [comment]
The fix for _openConnection _closeConnection has been merged in SocketRocket.
https://github.com/square/SocketRocket/issues/263

**Comment by lukeredpath** [comment]
Looks good to me so far, we should also include in this PR a bump of the main library up to 1.6.1.

**Comment by hamchapman** [comment]
Bumped the version of SocketRocket to 0.4.1 and the version of the pod itself to 1.6.1. Think I got all the references but could do with you checking it if possible @lukeredpath

**Comment by lukeredpath** [comment]
v1.6.1 now available via cocoapods, I still need to create a binary release though.

**Pull request merged**
